version: "3.2"
services:

  sqlServer:
    container_name: sqlServer
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Database.01"
      ACCEPT_EULA: "Y"